using System.Collections.Generic;
using System.IO;
using MigraDoc.DocumentObjectModel;
using MigraDoc.Rendering;
using MigraDoc.RtfRendering;
using WriteUp.Models;

namespace WriteUp.Services;

/// <summary>
/// Builds a MigraDoc document from a session and renders it to PDF (for
/// printing) and RTF (opens and edits natively in Word, save-as .docx).
/// One document model, two outputs — via the MIT-licensed PDFsharp/MigraDoc.
/// </summary>
public static class DocumentExporter
{
    private static readonly Color Accent = new(255, 76, 31);
    private static readonly Color Muted = new(107, 107, 107);

    public static void SavePdf(SessionMeta m, IReadOnlyList<Step> steps, string path, string pageSize = "Letter")
    {
        var doc = Build(m, steps, pageSize);
        var renderer = new PdfDocumentRenderer { Document = doc };
        renderer.RenderDocument();
        renderer.Save(path);
    }

    public static void SaveRtf(SessionMeta m, IReadOnlyList<Step> steps, string path, string pageSize = "Letter")
    {
        var doc = Build(m, steps, pageSize);
        var renderer = new RtfDocumentRenderer();
        renderer.Render(doc, path, Path.GetDirectoryName(path) ?? Environment.CurrentDirectory);
    }

    private static Document Build(SessionMeta m, IReadOnlyList<Step> steps, string pageSize)
    {
        var doc = new Document();
        doc.Info.Title = ReportWriter.TitleOf(m);
        if (!string.IsNullOrWhiteSpace(m.Author)) doc.Info.Author = m.Author;

        var normal = doc.Styles["Normal"];
        normal.Font.Name = "Segoe UI";
        normal.Font.Size = 10.5;

        var sec = doc.AddSection();
        sec.PageSetup.PageFormat = pageSize == "A4" ? PageFormat.A4 : PageFormat.Letter;
        sec.PageSetup.TopMargin = Unit.FromCentimeter(2);
        sec.PageSetup.BottomMargin = Unit.FromCentimeter(2);
        sec.PageSetup.LeftMargin = Unit.FromCentimeter(2);
        sec.PageSetup.RightMargin = Unit.FromCentimeter(2);

        // Footer: company + page number
        var footer = sec.Footers.Primary.AddParagraph();
        footer.Format.Font.Size = 8;
        footer.Format.Font.Color = Muted;
        footer.AddText((string.IsNullOrWhiteSpace(m.Company) ? "Generated by WriteUp" : m.Company) + "    Page ");
        footer.AddPageField();

        // Logo, right aligned
        string logoPath = Branding.LogoPath;
        if (!string.IsNullOrWhiteSpace(logoPath) && File.Exists(logoPath))
        {
            var lp = sec.AddParagraph();
            lp.Format.Alignment = ParagraphAlignment.Right;
            var logo = lp.AddImage(logoPath);
            logo.LockAspectRatio = true;
            logo.Height = Unit.FromCentimeter(1.1);
        }

        // Company / department
        if (!string.IsNullOrWhiteSpace(m.Company))
        {
            var cp = sec.AddParagraph();
            cp.AddFormattedText(m.Company, TextFormat.Bold).Size = 13;
            if (!string.IsNullOrWhiteSpace(m.Department))
            {
                var dp = sec.AddParagraph(m.Department);
                dp.Format.Font.Size = 9.5;
                dp.Format.Font.Color = Muted;
            }
        }

        // Accent rule
        var rule = sec.AddParagraph();
        rule.Format.Borders.Bottom.Width = 1.5;
        rule.Format.Borders.Bottom.Color = Accent;
        rule.Format.SpaceAfter = Unit.FromCentimeter(0.25);

        // Title
        var tp = sec.AddParagraph(ReportWriter.TitleOf(m));
        tp.Format.Font.Size = 22;
        tp.Format.Font.Bold = true;
        tp.Format.SpaceBefore = Unit.FromCentimeter(0.2);

        if (!string.IsNullOrWhiteSpace(m.Subtitle))
        {
            var sp = sec.AddParagraph(m.Subtitle);
            sp.Format.Font.Italic = true;
            sp.Format.Font.Size = 12;
            sp.Format.Font.Color = Muted;
        }

        // Meta line
        var bits = ReportWriter.MetaPairs(m);
        if (bits.Count > 0)
        {
            var mp = sec.AddParagraph();
            mp.Format.Font.Size = 9.5;
            mp.Format.SpaceBefore = Unit.FromCentimeter(0.15);
            mp.Format.SpaceAfter = Unit.FromCentimeter(0.3);
            for (int i = 0; i < bits.Count; i++)
            {
                mp.AddFormattedText(bits[i].Item1 + ": ", TextFormat.Bold);
                mp.AddText(bits[i].Item2);
                if (i < bits.Count - 1) mp.AddText("     ");
            }
        }

        // Steps grouped by app
        int n = 0;
        string? current = null;
        foreach (var s in steps)
        {
            if (!string.IsNullOrWhiteSpace(s.Context) && s.Context != current)
            {
                current = s.Context;
                var hp = sec.AddParagraph("IN " + s.Context.ToUpperInvariant());
                hp.Format.Font.Size = 10;
                hp.Format.Font.Bold = true;
                hp.Format.Font.Color = Accent;
                hp.Format.SpaceBefore = Unit.FromCentimeter(0.4);
                hp.Format.SpaceAfter = Unit.FromCentimeter(0.1);
            }

            n++;
            var pp = sec.AddParagraph();
            pp.Format.SpaceBefore = Unit.FromCentimeter(0.15);
            pp.AddFormattedText(n + ".  ", TextFormat.Bold);
            pp.AddText(s.Caption);

            if (s.HasScreenshot && File.Exists(s.ScreenshotPath!))
            {
                var ip = sec.AddParagraph();
                ip.Format.SpaceBefore = Unit.FromCentimeter(0.12);
                var img = ip.AddImage(s.ScreenshotPath);
                img.LockAspectRatio = true;
                img.Width = Unit.FromCentimeter(15);
            }
        }

        return doc;
    }
}
